version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    container_name: fastapi-app-portfolio
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env

  streamlit:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    container_name: streamlit-app-portfolio
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - api
    env_file:
      - ./.env

  postgres:
    image: ankane/pgvector
    container_name: postgres-portfolio
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: fastapi-pgadmin-portfolio
    env_file:
      - ./.env
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
